### ISSUE TITLE
Are you still working on Fluent/Suit integration?

### ISSUE THREAD

**Issue by mrmachine** [bashu/fluentcms-suit#1]
There's also https://github.com/ScottBarkman/fluent_suit which is a little old, but might be useful if you are still getting started?

**Comment by bashu** [comment]
yes, will be released soon

**Comment by bashu** [comment]
Hey @mrmachine

Can you try it and test before I release it?

**Comment by bashu** [comment]
@mrmachine try it https://pypi.python.org/pypi/fluentcms-suit/

**Comment by bashu** [comment]
@mrmachine hey you may find this interesting (in a future) https://github.com/bashu/awesome-fluentcms
